import { useRef } from "react"
import Head from "next/head"
import Avatar from "../components/Avatar"
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid"
import { SearchIcon } from "@heroicons/react/outline"
import Image from "next/image"
import Footer from "../components/Footer"
import { useRouter } from "next/router"

export default function Home() {
    const router = useRouter()
    const searchInputRef = useRef(null)

    const search = (e) => {
        e.preventDefault()
        const term = searchInputRef.current.value

        if (!term) return

        router.push(`/search?term=${term}`)
    }

    return (
        <div className="flex flex-col justify-center h-screen">
            <Head>
                <title>Google Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* HEADER */}
            <header className="flex w-full p-5 justify-between text-sm text-gray-500">
                {/* Left */}
                <div className="flex space-x-4 items-center">
                    <p className="link">
                        <a
                            href="https://about.google/?utm_source=google-RU&utm_medium=referral&utm_campaign=hp-footer&fg=1"
                            target="_blank"
                            rel="noreferrer"
                        >
                            About
                        </a>
                    </p>
                    <p className="link">
                        <a
                            href="https://chrome.google.com/webstore/category/extensions?hl=ru"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Store
                        </a>
                    </p>
                </div>

                {/* Right */}
                <div className="flex space-x-4 items-center">
                    <p className="link">
                        <a
                            href="https://mail.google.com/"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Gmail
                        </a>
                    </p>
                    <p className="link">
                        <a
                            href="https://www.google.ru/imghp?hl=ru&ogbl"
                            target="_blank"
                            rel="noreferrer"
                        >
                            Images
                        </a>
                    </p>

                    <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer transition duration-200 hover:transition hover:duration-200" />

                    <Avatar url="https://i.ibb.co/mDhcgFS/me-about.png" />
                </div>
            </header>

            {/* BODY */}
            <div className="flex flex-col items-center mt-44 flex-grow">
                <form className="flex flex-col items-center flex-grow w-4/5">
                    <Image
                        src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
                        alt="google logo"
                        height={100}
                        width={300}
                    />

                    <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center transition duration-200 hover:transition hover:duration-200 sm:max-w-xl lg:max-w-2xl">
                        <SearchIcon className="h-5 mr-3 text-gray-500" />
                        <input
                            ref={searchInputRef}
                            type="text"
                            className="focus:outline-none flex-grow"
                        />
                        <MicrophoneIcon className="h-5 text-gray-500 cursor-pointer hover:text-black transition duration-200 hover:transition hover:duration-200" />
                    </div>

                    <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
                        <button onClick={search} className="btn">
                            Google Search
                        </button>
                        <button onClick={search} className="btn">
                            I&#39;m Feeling Lucky
                        </button>
                    </div>
                </form>
            </div>

            {/* FOOTER */}
            <Footer />
        </div>
    )
}
